// Code generated by "some generator"; DO NOT EDIT.
package main

func main() {
	tooManyIfs()
}

func tooManyIfs() {
	if false {
	}

	if false {
	}

	if false {
	}

	if false {
	}

	if false {
	}

	if false {
	}

	if false {
	}

	if false {
	}

	if false {
	}

	if false {
	}
}
